# Site settings
title: Redlink Developers
email: support@redlink.io
description: "Redlink Developers site"
baseurl: ""
url: "http://dev.redlink.io"

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-redirect-from
